CREATE TABLE Battlegroup(
	id int primary key identity(1,1),
	owner_id int not null,
	size int not null,
	current_loc_id int not null,
	destination_loc_id int null,
	orders_id int null,
	group_speed int not null,
	str_mod float not null,
	dex_mod float not null,
	vit_mod float not null,
	pow_mod float not null,
	res_mod float not null,
	metal_mod float not null,
	stone_mod float not null,
	tree_mod float not null,
	food_mod float not null,
	build_mod float not null,
	movement_mod float not null,
	reproduction_mod float not null,
	loot_mod float not null,
	regen_mod int not null,
	resurrection_mod int not null,
	defense_mod int not null,
	CONSTRAINT fk_bg_user FOREIGN KEY (owner_id) REFERENCES Users(id),
	CONSTRAINT fk_bg_current FOREIGN KEY (current_loc_id) REFERENCES Location(id),
	CONSTRAINT fk_bg_destination FOREIGN KEY (destination_loc_id) REFERENCES Location(id),
	CONSTRAINT fk_bg_orders FOREIGN KEY (orders_id) REFERENCES Orders(id)
);