//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZwars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Battlegroup = new HashSet<Battlegroup>();
            this.MinionOwnership = new HashSet<MinionOwnership>();
            this.UserMovementHistory = new HashSet<UserMovementHistory>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public int experience { get; set; }
        public int lvl { get; set; }
        public int traits_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Battlegroup> Battlegroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MinionOwnership> MinionOwnership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMovementHistory> UserMovementHistory { get; set; }
        public virtual UserTraits UserTraits { get; set; }
    }
}
