//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VZwars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMovementHistory
    {
        public int id { get; set; }
        public int location_id { get; set; }
        public int users_id { get; set; }
        public System.DateTime occurence { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Users Users { get; set; }
    }
}
