//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinionWarsEntitiesLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvolutionPool
    {
        public int id { get; set; }
        public Nullable<System.DateTime> stored_date { get; set; }
        public int minion_id { get; set; }
        public System.Data.Entity.Spatial.DbGeography last_location { get; set; }
    
        public virtual Minion Minion { get; set; }
    }
}
