//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinionWarsEntitiesLib.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MinionWarsEntities : DbContext
    {
        public MinionWarsEntities()
            : base("name=MinionWarsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Battlegroup> Battlegroup { get; set; }
        public virtual DbSet<BattlegroupAssignment> BattlegroupAssignment { get; set; }
        public virtual DbSet<BattlegroupMovementHistory> BattlegroupMovementHistory { get; set; }
        public virtual DbSet<HiveNode> HiveNode { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Minion> Minion { get; set; }
        public virtual DbSet<MinionOwnership> MinionOwnership { get; set; }
        public virtual DbSet<MinionType> MinionType { get; set; }
        public virtual DbSet<ModifierCoeficients> ModifierCoeficients { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<ResourceNode> ResourceNode { get; set; }
        public virtual DbSet<ResourceType> ResourceType { get; set; }
        public virtual DbSet<UserMovementHistory> UserMovementHistory { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserTraits> UserTraits { get; set; }
    }
}
