//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinionWarsEntitiesLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTraits
    {
        public int id { get; set; }
        public int cbg_size { get; set; }
        public int cbg_count { get; set; }
        public double cbg_speed { get; set; }
        public double arch_speed { get; set; }
        public int arch_def { get; set; }
        public int arch_count { get; set; }
        public int pbg_size { get; set; }
    }
}
