//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinionWarsEntitiesLib.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMovementHistory
    {
        public int id { get; set; }
        public int users_id { get; set; }
        public System.DateTime occurence { get; set; }
        public System.Data.Entity.Spatial.DbGeography location { get; set; }
        public Nullable<double> activity_saturation { get; set; }
        public Nullable<double> event_saturation { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
